name: Build

on: [push, pull_request]

env:
  buildDir: ${{ github.workspace }}/build/

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/examplePlugin/CMakeLists.txt'
          buildDirectory: ${{ env.buildDir }}
          buildWithCMake: true
